@startuml "Container"

' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include ../common/C4_Container.puml

LAYOUT_WITH_LEGEND()

title Container diagram for Warmhouse smart home system (Improved)

Person(user, "User", "Warmhouse user")

System_Ext(device, "Device", "Smart home device with open-source protocol")

Enterprise_Boundary(warmhouse_boundary, "Warmhouse") {
    Container(warmhouse_mobile_app, "Mobile App", "Provides Warmhouse functionality to user via their mobile device")
    Container(warmhouse_web_app, "Web Application", "Delivers the static content and the Warmhouse SPA for UI")
    Container(warmhouse_spa, "Single-Page App", "Provides Warmhouse functionality to users via their web browser")
    
    Container(warmhouse_proxy_service, "Proxy", "Service for balancing device connections")
    Container(warmhouse_connections_service, "Connections Service", "Service for 2-way interaction with devices")
    
    Container(warmhouse_device_control_backend_api, "Device Control API", "Provides API for controlling devices")
    Container(warmhouse_scenarios_backend_api, "Scenarios API", "Provides API for managing and inferring scenarios")
    Container(warmhouse_authorization_backend_api, "Authorization API", "Provides API for authorizing and registering users")
    Container(warmhouse_device_management_backend_api, "Device Management API", "Provides API for connecting devices and managing their meta info")

    ContainerDb(warmhouse_users_info_db, "Users Info DB", "Stores users' info: accounts, devices lists, scenarios, etc.")

    Container(warmhouse_monitoring_service, "Monitoring Service", "Processes incoming device state updates")
    
    Container(warmhouse_device_state_storage_backend_api, "Device State Storage API", "Provides API for storing and retrieving device states")
    ContainerDb(warmhouse_device_state_db, "Device State DB", "Stores device states")
    
    Container(warmhouse_realtime_service, "Realtime Service", "Delivers real-time device state updates")
}

Rel(user, warmhouse_web_app, "Uses", "HTTPS")
Rel(user, warmhouse_spa, "Uses", "HTTPS")
Rel(user, warmhouse_mobile_app, "Uses", "Mobile interface")

Rel(device, warmhouse_proxy_service, "Connects to / sends updates", "WebSocket")

Rel(warmhouse_mobile_app, device, "Shares auth token / gets info", "Bluetooth")
Rel(warmhouse_mobile_app, warmhouse_web_app, "Reuses", "HTTPS")
Rel(warmhouse_mobile_app, warmhouse_spa, "Reuses", "HTTPS")

Rel(warmhouse_web_app, warmhouse_spa, "Delivers", "Static content")

Rel(warmhouse_spa, warmhouse_device_control_backend_api, "Controls devices via", "JSON/HTTPS")
Rel(warmhouse_spa, warmhouse_scenarios_backend_api, "Manages scenarios via", "JSON/HTTPS")
Rel(warmhouse_spa, warmhouse_device_state_storage_backend_api, "Gets last device states via", "JSON/HTTPS")
Rel(warmhouse_spa, warmhouse_realtime_service, "Establishes SSE connection for real-time updates", "Server-Sent Events")
Rel(warmhouse_spa, warmhouse_authorization_backend_api, "Authenticates via", "JSON/HTTPS")
Rel(warmhouse_spa, warmhouse_device_management_backend_api, "Manages devices via", "JSON/HTTPS")

Rel(warmhouse_proxy_service, device, "Passes directives to", "WebSocket")
Rel(warmhouse_proxy_service, warmhouse_connections_service, "Passes device updates to / balances across", "WebSocket")

BiRel(warmhouse_connections_service, warmhouse_proxy_service, "Heartbeats / directives", "HTTP / WebSocket")
Rel(warmhouse_connections_service, warmhouse_monitoring_service, "Sends device state updates", "async, JSON/HTTPS")

Rel(warmhouse_device_control_backend_api, warmhouse_proxy_service, "Resolves proxy host via", "JSON/HTTPS")
Rel(warmhouse_device_control_backend_api, warmhouse_connections_service, "Passes directives via", "JSON/HTTPS")

Rel(warmhouse_scenarios_backend_api, warmhouse_device_control_backend_api, "Sends directives via", "JSON/HTTPS")
Rel(warmhouse_scenarios_backend_api, warmhouse_users_info_db, "Stores scenarios to", "HTTPS")
BiRel(warmhouse_scenarios_backend_api, warmhouse_monitoring_service, "Subscribes to updates via / Sends device state updates to", "sync/async, JSON/HTTPS")

Rel(warmhouse_device_state_storage_backend_api, warmhouse_device_state_db, "Stores historical data to", "JSON/HTTPS")
BiRel(warmhouse_device_state_storage_backend_api, warmhouse_monitoring_service, "Subscribes to updates via / Sends device state updates to", "sync/async, JSON/HTTPS")

BiRel(warmhouse_realtime_service, warmhouse_monitoring_service, "Subscribes to updates via / Sends device state updates to", "sync/async, JSON/HTTPS")

Rel(warmhouse_authorization_backend_api, warmhouse_users_info_db, "Stores user info to", "JSON/HTTPS")

Rel(warmhouse_device_management_backend_api, warmhouse_users_info_db, "Stores device info to", "JSON/HTTPS")

@enduml